version: '3.8'

services:
  email-classifier-dashboard:
    build: .
    ports:
      - "8501:8501"
    volumes:
      # Mount data files if they exist locally
      - ./emails_cleaned.csv:/app/emails_cleaned.csv:ro
      - ./tfidf_vectorizer.pkl:/app/tfidf_vectorizer.pkl:ro
      - ./naive_bayes_tfidf.pkl:/app/naive_bayes_tfidf.pkl:ro
      - ./svm_tfidf.pkl:/app/svm_tfidf.pkl:ro
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
